### ISSUE TITLE
[Proposal] Block reward

### ISSUE THREAD

**Issue by aleoweb123** [AleoHQ/snarkVM#2080]
## 💥 Proposal

After block height 62886, the staking status is as follows:
```json
{
"starting_round": 153352,
"members": {
"aleo1q6qstg8q8shwqf5m6q5fcenuwsdqsvp4hhsgfnx5chzjm3secyzqt9mxm8": [
100379441586578,
true
],
"aleo1k8yf2kfajalpqtxu95vstcf9599vp0sm47fvt8a0n3md7xxv9s9qvsktd2": [
100379443477748,
true
],
"aleo1waeqqedtk8rszj7yc567x73m533hc3emv66drpa9vwypps3tlupqkg8ve2": [
100379443477748,
false
],
"aleo14yr9gw824yp95fpwfvyq0q5zka088g530chltrsvpsjpusqupgrqlgcu84": [
100379443477748,
false
]
},
"total_stake": 401517772019822
}
```
At block height 62887, a delegation staking event occurred where aleo1q6qstg8q8shwqf5m6q5fcenuwsdqsvp4hhsgfnx5chzjm3secyzqt9mxm8 increased by 36,000,000.

After block height **62887**, the updated staking status is as follows:
```json
{
"starting_round": 153354,
"members": {
"aleo1q6qstg8q8shwqf5m6q5fcenuwsdqsvp4hhsgfnx5chzjm3secyzqt9mxm8": [
100379467586578,
true
],
"aleo1k8yf2kfajalpqtxu95vstcf9599vp0sm47fvt8a0n3md7xxv9s9qvsktd2": [
100379449423333,
true
],
"aleo1waeqqedtk8rszj7yc567x73m533hc3emv66drpa9vwypps3tlupqkg8ve2": [
100379449423333,
false
],
"aleo14yr9gw824yp95fpwfvyq0q5zka088g530chltrsvpsjpusqupgrqlgcu84": [
100379449423333,
false
]
},
"total_stake": 401517815856577
}
```
However, this situation is quite unique, and I have some doubts. In the starting round 153352, aleo1q6qstg8q8shwqf5m6q5fcenuwsdqsvp4hhsgfnx5chzjm3secyzqt9mxm8 should have been among those with less than 25% stake, which means it should have earned rewards. But in the data for starting round 153354, aleo1q6qstg8q8shwqf5m6q5fcenuwsdqsvp4hhsgfnx5chzjm3secyzqt9mxm8 does not show any rewards.

I believe that aleo1q6qstg8q8shwqf5m6q5fcenuwsdqsvp4hhsgfnx5chzjm3secyzqt9mxm8 should have received the rewards. Similarly, if Alex stakes at height_a, I believe that the rewards at height_a should not be allocated to Alex. Alex's rewards should start from height_a+1 onwards.

**Comment by HarukaMa** [comment]
Events happen in this order:

1. All transitions are executed. The stake for the `q6q` address increases here. At this time the stake for it has exceeded 25%.
2. Post ratify is executed. 25% check happens now when nodes calculate the stake rewards. `q6q` and all stakers will not receive rewards because of this.

If this is not the case, we will actually allow 25+% receive rewards.

Also, unstaking has 1h cooldown (360 blocks), so I don't really think height+1 matters that much.

**Comment by aleoweb123** [comment]
Hmm, the reason for the issue is that "All transitions" were executed first.
In reality: Shouldn't the newly added delegation at height_a not take away the "block reward" for that height? Would it be more reasonable to use the staking status before the start of block production when calculating it?

**Comment by HarukaMa** [comment]
IMO it doesn't matter that much as it will "take away" the reward for the next block anyway. I don't see the 1-block difference though, could you elaborate why this would be an issue?

**Comment by aleoweb123** [comment]
Suppose there are 10 validators, and at height 9999, each validator stakes 1 million tokens.  The expected yield for each validator should be 10%.

However, at height 10000, when Alex delegates and stakes 1 million tokens to one of the validators, according to the current algorithm, the yield for each validator becomes 9.09%.

Of course, if Alex initiates a withdrawal at height 20000, according to the current algorithm, height 20000 would not provide any yield to Alex.

**Comment by HarukaMa** [comment]
If those 2 steps are reversed:

1. At block 10000 every validator still has 10% of the block reward, then it becomes ~9.09% at block 10001; it's just delayed by one block.
2. At block 20000, Alex will receive the staking reward, but at block 10000, Alex won't because the reward happens before transitions are executed; it's just delayed by one block (`[10000, 19999]` vs `[10001, 20000]`).

However, in both order:

Alex won't receive the reward anyway as after he stakes to that validator, he pushed the validator over 25%.

Personally, I prefer the "state changes take effect immediately" rather than "state changes are delayed by one block", as the former feels cleaner and there should be no reason to add artificial delays.

I've edited this comment so many times already, but just realized what you are asking for is essentially this 1-block delay: I'm curious if there are more reasons behind that?

**Comment by aleoweb123** [comment]
😄 Actually, I think it would be more reasonable to allocate a staking amount corresponding to the height of 20,000 to Alex since he extracted during that interval.

We encountered an issue while presenting Validator data.  When calculating staking rewards, we assumed that the earnings from new blocks would be distributed according to the ratio of the previous staking.  However, we observed some discrepancies in the data.  Although it is possible to fix the issue by making a simple modification to our statistical method, we still want to understand the underlying cause.

**Comment by HarukaMa** [comment]
I'm aware that you will need to completely understand the snarkOS's behavior to precisely compute the staker / validator balances (I'm going through that pain as well, and that's part of why my explorer is still offline right now).

_Ignoring the 25% issue_, I still don't think there will be a model that could give Alex both the rewards for block 10000 and block 20000. You give him the reward for block 20000, then you can't also count block 10000 if everything is executed in the fixed order. Remember that if we don't give him the reward at block 20000, he will get the reward for the block when he initially staked in (which is block 10000). If we can only count once, then I personally prefer the more straightforward way - counting everything in the same block.

In other words, we are not giving the reward since he unstaked during block 20000, but we gave the reward when he staked at block 10000. Still pretty fair IMO.

<hr>

edit insertion: then I realized you want the staker to have both rewards - _technically_ it's still possible to add both ends, but it would lead to a very complicated calculation just for this one block of reward. And it will lead to a side effect that the unbinding staker receives the reward but not contributing to the validator voting. 

<hr>

edit inside edit: and remember that he unstaked and still taking part of the rewards for other still staking stakers. Would you call that fair?

<hr>

If we take the 25% into the consideration, then why would we give him any of the reward, since he staked with a validator with 25+% of the total stake? That's one of the rule of the network as well.

**Comment by aleoweb123** [comment]
No, I believe there are no rewards at height 10,000, but rewards can be obtained at height 20,000. It's not that rewards are received on both ends. This is because after block 9,999, Alex had not yet participated in staking, but after block 19,999, Alex was in a staking state.

**Comment by HarukaMa** [comment]
After block 10000, he has participated in staking and it has affected the validators by the time the ratifications are processed, and after block 20000, he is no longer affecting other stakers and validators.

Still, why should we change the order here?

**Comment by aleoweb123** [comment]
Thank you very much for your response. This is just a critical value issue. I will recalculate our data according to the current method.

**Comment by aleoweb123** [comment]
I'm glad we addressed this issue.
In the "staking_rewards" method, all the earnings of the stakers are recorded.
https://aleo123.io/validators
