### ISSUE TITLE
[Bug] There is a block where all solution rewards are 0, which is unreasonable

### ISSUE THREAD

**Issue by elderhammer** [AleoHQ/snarkVM#2323]
## 🐛 Bug Report

ab1v24j6eqh75v3dgr3fwkgmv7zcun076gcdg8wz58y4c7w3pnufc9sfdahmc
https://aleo123.io/block/1231470

**Comment by raychu86** [comment]
Need to dig deeper and determine what changes are possibly needed, but here are some observations:

It looks like the reason there is 0 puzzle rewards in this block is due to how we are updating the coinbase targets.

If you look at block [1231469](https://api.explorer.aleo.org/v1/testnet3/block/1231469), you'll see that we've reached a `cumulative_proof_target` of 4296788923, which is less than the `coinbase_target` of block [1231468](https://api.explorer.aleo.org/v1/testnet3/block/1231468). However, due to the target adjustment algorithm, the new coinbase target for block 1231469 is less than the `cumulative_proof_target`.

This means that for block [1231470](https://api.explorer.aleo.org/v1/testnet3/block/1231470), our ratio of remaining rewards for that target is 0, thus the empty reward.

**Comment by randomsleep** [comment]
I submitted some bug reports about the PoW part at HackerOnce several days ago. I think this is a bug of incorrect updating `coinbase_target`, (report 2315260).
