### ISSUE TITLE
[Bug] Transition with the same value output  will conflict

### ISSUE THREAD

**Issue by randomsleep** [AleoHQ/snarkVM#2332]
## 🐛 Bug Report

Currently, it will return an error if the transition output is the same. 

https://github.com/AleoHQ/snarkVM/blob/ce4ea932be410e803a996d3663fe36cd214a15eb/synthesizer/program/src/function/mod.rs#L163

This will cause unwanted behavior.

## Steps to Reproduce

Run this function:

```
program test_output.aleo {
    transition double_output() -> (u64, u64) {
        return (0u64, 0u64);
    }
}
```

Find that:

```
leo run -d --offline --enable-dce-ast-snapshot double_output
       Leo ✅ Compiled 'main.leo' into Aleo instructions
       Leo ✅ Compiled 'token.leo' into Aleo instructions
Cannot add duplicate output statement
Error [ECLI0377008]: Failed to execute the `build` command.
SnarkVM Error: Failed to parse string. Parsing Error: VerboseError { errors: [("\n", Nom(MapRes)), ("\n\n\n\nfunction double_output:\n    output 0u64 as u64.private;\n    output 0u64 as u64.private;\n", Nom(Alt)), ("\n\n\n\nfunction double_output:\n    output 0u64 as u64.private;\n    output 0u64 as u64.private;\n", Nom(Many1))] }
```

## Expected Behavior

Should run successfully.

## Your Environment

leo 1.10.0

**Comment by d0cd** [comment]
snarkVM requires `Output` statements to be unique, since it uses the register locator to determine a record's index.
See [here](https://github.com/AleoHQ/snarkVM/blob/5daa1ab6ad1c07af48db6877bbe045a39ba32d57/console/program/src/response/mod.rs#L158).
Without this restriction, your transition can produce two records with the same `OutputID`. 
Instead, this should be fixed at the Leo level, with sufficient warnings or a modification to code generation that accounts for duplicate output values.

I've added a tracking issue [here](https://github.com/AleoHQ/leo/issues/27638).

Please feel free to re-open if you believe the issue still needs to be addressed at the snarkVM level.
