### ISSUE TITLE
bug: incorrect timestamp in explorer

### ISSUE THREAD

**Issue by alexanderblv** [AleoHQ/snarkVM#2432]
![image](https://github.com/AleoHQ/snarkVM/assets/137616408/cdfcf595-d570-4d90-a6ea-23b756d0301d)

Apparently, timestamps have become incorrectly displayed for programs. This may be a problem in the future. I do not know which repository is suitable for this problem, so I open it here.

https://explorer.aleo.org/program/credits.aleo

**Comment by iamalwaysuncomfortable** [comment]
Hey Alexander, this is due to credits.aleo being present in the Genesis block. The timestamp in that block is the beginning of the Unix Epoch which does indeed begin 54 years ago! 

Just as a note, any issue found with explorer or aleo.tools should be directed to https://github.com/AleoHQ/sdk/issues. Thanks for bringing your concerns to attention.
