### ISSUE TITLE
Merkle tree on PedersenCRH fails to produce correct root hash

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#244]
When computing the root hash of a Merkle tree using `PedersenCRH` on `Projective`, the computed root hash doesn't match the root hash returned by the `MerkleTree`.

There are two tests with `TODOs` currently marked `#[ignore]` which test for these failing cases, and can be found in `snarkos-algorithms/src/merkle_tree/tests.rs` following PR AleoHQ/snarkOS#273 . In the same test file, you will see all other test cases are currently passing.

**Comment by ljedrz** [comment]
Confirmed: the 2 `#[ignore]`d tests still panic.

**Comment by Pratyush** [comment]
The issue is just that the projective representation is not meant to be unique. That is, the additional coordinates (eg: Z in the short weierstrass case) can be different across two equivalent representations for the same point. so when you convert it to bytes, the part corresponding to the z coordinate differs. To get around this, in the conversion to bytes I would convert it to affine first.

**Comment by weikengchen** [comment]
Likely it has been fixed in testnet2. 

It is discovered because the Merkle tree gadget does not agree with the native implementation. The solution is to require the Bowe-Hopwood and Pedersen CRH to use the affine element as the output. 

Related PR: #260

**Comment by ljedrz** [comment]
The 2 currently `#[ignore]`d tests now do pass;' it would be a good idea to un-ignore them now that they should be passing.

**Comment by howardwu** [comment]
Thanks @ljedrz. I will keep this into account as I'm updating DPC at the moment for `testnet2` branch

**Comment by ljedrz** [comment]
The aforementioned 2 tests were un-ignored in https://github.com/AleoHQ/snarkVM/pull/298.
