### ISSUE TITLE
No need to create a credits with microcredits =0

### ISSUE THREAD

**Issue by 0xsaya** [AleoHQ/snarkVM#2445]
When a user transfers all of their microcredits to the "to" address, in addition to creating a credits record for the "to" address, a credits record with microcredits set to 0 is also created for the "from" address. Generating a large number of credits records with microcredits set to 0 can cause wastage of network resources.

https://github.com/AleoHQ/snarkVM/blob/1485bdd42a6156e09dc09066b262302df9252bf0/synthesizer/program/src/resources/credits.aleo#L792

**Comment by damons** [comment]
Need to know the impact of the "wastage."  Still, wouldn't block mainnet for this.

Can you demonstrate the impact of the waste?

**Comment by raychu86** [comment]
These 0 balance records are necessary to preserve privacy. A `transfer_private` call should always have the same number of inputs and outputs in order to reveal as little information about the amounts/data as possible, even if a record is considered "wasted" due to a balance of 0. 

I am closing this due because this is a desired property of our system.
